import {
    Sparkles,
    Wallet,
    CreditCard,
    Tags,
    ArrowLeftRight,
    Target,
    ListChecks,
    PartyPopper
} from 'lucide-react';

export const ONBOARDING_STEPS = [
    {
        id: 'welcome',
        title: 'Bem-vindo ao Minhas Finanças! 🎉',
        description: 'Vamos configurar o app juntos! Você vai poder criar suas contas, categorias e muito mais enquanto aprende.',
        icon: Sparkles,
        targetId: null,
        position: 'center',
        requiresAction: false,
    },
    {
        id: 'navigate-settings',
        title: 'Vá para Configurações',
        description: 'Primeiro, vamos acessar as configurações onde você pode adicionar suas contas bancárias e cartões.',
        icon: Wallet,
        targetId: 'nav-configuracao',
        position: 'top',
        requiresAction: true,
        actionHint: 'Clique no ícone de configurações (usuário) abaixo',
        nextTrigger: 'page:configuracao',
    },
    {
        id: 'accounts-info',
        title: 'Contas Bancárias',
        description: 'Aqui você pode adicionar suas contas bancárias. Cada conta mantém seu saldo separado para melhor organização.',
        icon: Wallet,
        targetId: null,
        position: 'center',
        requiresAction: false,
    },
    {
        id: 'cards-info',
        title: 'Cartões de Crédito',
        description: 'Adicione seus cartões para acompanhar faturas, limites e vencimentos. Tudo em um só lugar!',
        icon: CreditCard,
        targetId: null,
        position: 'center',
        requiresAction: false,
    },
    {
        id: 'navigate-transactions',
        title: 'Vá para Movimentações',
        description: 'Agora vamos ver onde você registra suas receitas e despesas do dia a dia.',
        icon: ArrowLeftRight,
        targetId: 'nav-movimentacao',
        position: 'top',
        requiresAction: true,
        actionHint: 'Clique no ícone de setas (movimentação) abaixo',
        nextTrigger: 'page:movimentacao',
    },
    {
        id: 'transactions-info',
        title: 'Registre suas Transações',
        description: 'Use o botão + para adicionar receitas, despesas ou transferências. Você pode categorizar cada transação!',
        icon: ArrowLeftRight,
        targetId: null,
        position: 'center',
        requiresAction: false,
    },
    {
        id: 'navigate-goals',
        title: 'Vá para Metas',
        description: 'Defina seus objetivos financeiros e acompanhe o progresso visualmente.',
        icon: Target,
        targetId: 'nav-metas',
        position: 'top',
        requiresAction: true,
        actionHint: 'Clique no ícone de alvo (metas) abaixo',
        nextTrigger: 'page:metas',
    },
    {
        id: 'goals-info',
        title: 'Suas Metas Financeiras',
        description: 'Crie metas para viagens, reserva de emergência, compras importantes. Veja seu progresso com gráficos motivadores!',
        icon: Target,
        targetId: null,
        position: 'center',
        requiresAction: false,
    },
    {
        id: 'navigate-shopping',
        title: 'Vá para Lista de Compras',
        description: 'Organize suas compras do mês de forma simples e prática.',
        icon: ListChecks,
        targetId: 'nav-lista',
        position: 'top',
        requiresAction: true,
        actionHint: 'Clique no ícone de lista abaixo',
        nextTrigger: 'page:lista',
    },
    {
        id: 'complete',
        title: 'Tudo Pronto! 🚀',
        description: 'Você conheceu as principais funcionalidades! Explore à vontade e lembre-se: consistência é a chave para o controle financeiro.',
        icon: PartyPopper,
        targetId: null,
        position: 'center',
        requiresAction: false,
    },
];

export default ONBOARDING_STEPS;
